apiVersion: v1
kind: Service
metadata:
  name: static-web-service
  namespace: sample
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 31000
  selector:
    app: days-app
